# Question 1
 Write a function so that the columns of the output matrix are powers of the input vector.
 The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [1]:
import numpy as np
import pandas as pd

In [9]:
a=[]
n=int(input("Number of elements in array:"))
for i in range(0,n):
    l=int(input())
    a.append(l)
print(a)    

Number of elements in array:5
4
5
6
3
5
[4, 5, 6, 3, 5]


In [12]:
def vandermonde(a,N):
    OP=np.vander(np.array(a), N)
    print (OP)

In [13]:
vandermonde(a,4)

[[ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]
 [ 27   9   3   1]
 [125  25   5   1]]


# Problem Statement 2:

 Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
 the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
 The moving averages with k=4 of a ten-value sequence (n=10) is shown below

In [16]:
def moving_window(seq, k):
    final = []
    for i in range(len(seq)-k+1):
        final.append(np.round(np.mean([seq[i+m] for m in range(k)]), 2))
    return final


print(moving_window([10,20,30,40,50,60,70,80,90,100], 4))

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
